global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  resolution: 0.05
  static_map: true

local_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  resolution: 0.05
  rolling_window: true
  width: 3.0
  height: 3.0
  static_map: false

costmap_common_params:
  obstacle_range: 2.5
  raytrace_range: 3.0
  footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
  inflation_radius: 0.5
  obstacle_layer:
    enabled: true
    max_obstacle_height: 2.0
  inflation_layer:
    enabled: true
